### PR TITLE
support VS2015

### LINKED ISSUE #1: Support VS 2015

### PR DESCRIPTION
**Pull request by Ekopalypse**
closes #1

### CODE REVIEW

**Comment by dail8859** [comment]
Does the `sln` file need updated as well for setting the Visual Studio version? Since it has worked thus far it doesn't seem to matter too much obviously :)

**Comment by Ekopalypse** [comment]
To make it work, no, but I assume it will matter, if one has VS2015 and VS2017 installed in parallel to get the correct one opened. 
So maybe for 2015
\# Visual Studio 14
VisualStudioVersion = 14.0.25420.1
and for 2017
\# Visual Studio 15
VisualStudioVersion = 15.0.25420.1

BUT I see that vcxproj and vcxproj.user do also have ToolsVersion field which seems to be set accordingly. Let me create two native windows dll projects and see what differs.

**Comment by dail8859** [comment]
> Let me create two native windows dll projects and see what differs.

Good idea.

**Comment by Ekopalypse** [comment]
I guess I'm done - what do you think?

**Comment by dail8859** [comment]
LGTM! Thanks!

**Pull request merged**
